version: '3.8'
services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5001:5000"
    environment:
      LT_LOAD_ONLY: th,en
    restart: unless-stopped
